version: '2'
services:
  mtail:
    build: mtail
    command:
      - "-progs"
      - "/etc/mtail"
      - "-logs"
      - "/var/log/chia/debug.log"
      - "-logtostderr"
    volumes:
      - c:/Users/retzk/.chia/mainnet/log/:/var/log/chia/
  chia_exporter:
    build: chia_exporter
    command:
      - "-cert"
      - "/etc/chia.crt"
      - "-key"
      - "/etc/chia.key"
      - "-url"
      - "https://host.docker.internal:8555"
    volumes:
      - c:/Users/retzk/.chia/mainnet/config/ssl/full_node/private_full_node.crt:/etc/chia.crt
      - c:/Users/retzk/.chia/mainnet/config/ssl/full_node/private_full_node.key:/etc/chia.key
  prometheus:
    build: prometheus
    volumes:
      - prom_data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    build: grafana
    ports:
      - "3000:3000"
volumes:
  prom_data:
