global:
  scrape_interval:     10s
  evaluation_interval: 10s
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9182']
  - job_name: 'mtail'
    static_configs:
      - targets: ['mtail:3903']
  - job_name: 'chia'
    static_configs:
      - targets: ['chia_exporter:9133']
